import { Header } from "@/components/Header"
import { Navbar } from "@/components/Navbar"
import style from '../styles/layout.module.css'


export const metadata = {
  title: 'My Products',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={style.container}>
        <Header title="My Products"/>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
